site_name: pandas-bootstrap

theme:
  name: "material"
  custom_dir: docs/overrides
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.expand
    - navigation.top
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_name: pandas-bootstrap
repo_url: https://github.com/williambdean/pandas-bootstrap
edit_uri: blob/main/docs/
site_url: https://williambdean.github.io/pandas-bootstrap

extra:
  homepage: https://williambdean.github.io/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/williambdean/pandas-bootstrap

nav:
  - Overview: index.md
  - Modules:
    - extensions.md
    - bootstrap.md
    - datasets.md
  - Examples:
    - Linear Regression: examples/linear-regression.md
    - examples/correlation.md
    - examples/return-type.md
    - examples/parallelization.md
    - examples/groupby-input.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
